# Start from the pytorch image
FROM pytorch/pytorch:2.0.0-cuda11.7-cudnn8-runtime
WORKDIR /
RUN apt-get update && apt-get install -y git
RUN git clone https://github.com/facebookresearch/llama.git
WORKDIR /llama
RUN python setup.py install
RUN pip install -r requirements.txt