# Start from the pytorch image
# FROM pytorch/pytorch:1.8.0-cuda11.7-cudnn8-runtime
FROM nvcr.io/nvidia/pytorch:23.01-py3
WORKDIR /
RUN apt-get update && apt-get install -y git
RUN git clone https://github.com/facebookresearch/llama.git
WORKDIR /llama
RUN python setup.py install
RUN pip install -r requirements.txt